version: '3.7'
services:
  moneytransfer:
    image: "money-transfer:latest"
    build:
      context: backendServices
      dockerfile: Dockerfile
    ports:
      - 5050:5050
      - 5051:5051

  moneyTransferUi:
    image: "money-transfer-ui:latest"
    build:
      context: UI/banking-ui
      dockerfile: Dockerfile
    ports:
      - 4200:4200
    links:
      - moneytransfer
