version: '3.7'
services:
  moneyTransfer:
    image: "money-transfer:latest"
    build:
      context: backendServices
      dockerfile: Dockerfile
#    container_name: money-transfer
    restart: "no"
    privileged: true
    network_mode: "host"
    volumes:
      - ./backendServices/target/liberty/wlp/usr/servers:/servers
    ports:
      - 5050:5050
      - 5051:5051

  moneyTransferUi:
    image: "money-transfer-ui:latest"
    build:
      context: UI/banking-ui
      dockerfile: Dockerfile
#    container_name: money-transfer-ui
    ports:
      - 4200:4200
    links:
      - moneyTransfer
